/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pointage;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author AlassaneOusmane
 */
public class AbsenceJFrame extends javax.swing.JFrame {
    Connection conn=null;
PreparedStatement requete=null;
ResultSet resultat=null;
public static String Matricule_p=null,hr_d=null,hr_fin=null;
Date dateabs=new Date();
private void Majtable(){
    Date date=new Date();
 SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        StringBuilder dateactuelle=new StringBuilder(sdf.format(date));
String sql="SELECT  personnel.matricule_personnel,nom, prenom, entitule, hr_debut, hr_fin, salle"+
"  FROM personnel, privilege, dispenser, matiere"+
" WHERE personnel.id_privilege = privilege.id_privilege"+
" AND privilege.libelle =  'professeur'"+
" AND personnel.matricule_personnel = dispenser.matricule_personnel"+
" AND matiere.code_matiere = dispenser.code_matiere"+
" AND dispenser.date =  '"+dateactuelle+"'";
        try {
            requete=(PreparedStatement) conn.prepareStatement(sql);
            resultat=requete.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
          
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
           
        }


}
    /**
     * Creates new form AbsenceJFrame
     */
    public AbsenceJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendarPopup1 = new org.jbundle.thin.base.screen.jcalendarbutton.JCalendarPopup();
        aujourdhui = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ajoutabsence = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        motif = new javax.swing.JTextArea();

        javax.swing.GroupLayout jCalendarPopup1Layout = new javax.swing.GroupLayout(jCalendarPopup1);
        jCalendarPopup1.setLayout(jCalendarPopup1Layout);
        jCalendarPopup1Layout.setHorizontalGroup(
            jCalendarPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jCalendarPopup1Layout.setVerticalGroup(
            jCalendarPopup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        aujourdhui.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        aujourdhui.setForeground(new java.awt.Color(0, 102, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        ajoutabsence.setText("Marquer absent");
        ajoutabsence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutabsenceMouseClicked(evt);
            }
        });

        motif.setColumns(20);
        motif.setFont(new java.awt.Font("Monospaced", 2, 13)); // NOI18N
        motif.setRows(5);
        motif.setText("pas de motif!");
        jScrollPane2.setViewportView(motif);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(ajoutabsence, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aujourdhui, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aujourdhui, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(ajoutabsence)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 97, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-805)/2, (screenSize.height-532)/2, 805, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ajoutabsence.setVisible(false);
        motif.setVisible(false);
        conn=(Connection) mysqlConnect.ConnectionDB();
        Date date=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/yyyy");
        StringBuilder dateactuelle=new StringBuilder(sdf.format(date));
        aujourdhui.setText(" Aujourd'hui le :"+dateactuelle);
        Majtable();
      
    }//GEN-LAST:event_formWindowOpened

    private void ajoutabsenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutabsenceMouseClicked
        // TODO add your handling code here:
         Date date=new Date();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        StringBuilder dateactuelle=new StringBuilder(sdf.format(date));
          String sql="INSERT INTO `pointage`.`absence` (`MATRICULE_PERSONNEL`, `HR_DEBUT`, `HR_FIN`, `MOTIF`, `DATE_ABSENCE`) VALUES ( ?, ?,?, ?, ?);";
        try {
            requete=(PreparedStatement) conn.prepareStatement(sql);
       
            requete.setString(1, Matricule_p);
            requete.setString(2, hr_d);
            requete.setString(3, hr_fin);
            requete.setString(4, motif.getText());
            requete.setString(5, dateactuelle.toString());
            requete.execute();
            Majtable();
            JOptionPane.showMessageDialog(null, "Ajouté");
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_ajoutabsenceMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        ajoutabsence.setVisible(true);
        motif.setVisible(true);
        int ligne=jTable1.getSelectedRow();
        Matricule_p=jTable1.getModel().getValueAt(ligne, 0).toString();
        hr_d=jTable1.getModel().getValueAt(ligne, 4).toString();
        hr_fin=jTable1.getModel().getValueAt(ligne, 5).toString();
     
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AbsenceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AbsenceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AbsenceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AbsenceJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new AbsenceJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajoutabsence;
    private javax.swing.JLabel aujourdhui;
    private org.jbundle.thin.base.screen.jcalendarbutton.JCalendarPopup jCalendarPopup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea motif;
    // End of variables declaration//GEN-END:variables
}
