/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pointage;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Panel;
import java.awt.ScrollPane;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import net.proteanit.sql.DbUtils;
import t2s.son.LecteurTexte;

/**
 *
 * @author AlassaneOusmane
 */
public class PersonnelJFrame extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement requete=null;
ResultSet resultat=null;
String id_privilege=null;
private void remplirCombox(){

String sql="select * from privilege";
        try {
            requete=(PreparedStatement) conn.prepareStatement(sql);
            resultat=requete.executeQuery();
            while(resultat.next()){
            
            jComboBox1.addItem(resultat.getString("libelle"));
           
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

}
private void Majtable(){

String sql="SELECT matricule_personnel,nom,prenom,email,adresse,telephone,statut libelle FROM   personnel";
        try {
            requete=(PreparedStatement) conn.prepareStatement(sql);
            resultat=requete.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
          
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
           
        }


}
    /**
     * Creates new form PersonnelJFrame
     */
    public PersonnelJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdajoutpersonnel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmatricule = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtadresse = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttelephone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtstatut = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox();
        txtprivilege = new javax.swing.JTextField();
        cmdSupprimer = new javax.swing.JButton();
        cmdModifier = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cmdajoutpersonnel.setText("Ajouter");
        cmdajoutpersonnel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdajoutpersonnelMouseClicked(evt);
            }
        });

        jLabel1.setText("PERSONNELS");

        jLabel2.setText("Matricule :");

        jLabel3.setText("Privilege");

        jLabel4.setText("Nom :");

        jLabel5.setText("Prenom :");

        jLabel6.setText("Email :");

        jLabel7.setText("Adresse :");

        jLabel8.setText("Telephone :");

        jLabel9.setText("Statut :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Matricule ", "Nom", "Prenom", "Email", "Adresse", "Telephone", "Statut"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        cmdSupprimer.setText("Supprimer");
        cmdSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdSupprimerMouseClicked(evt);
            }
        });

        cmdModifier.setText("Modifier");
        cmdModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdModifierMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmdajoutpersonnel)
                                .addGap(72, 72, 72)
                                .addComponent(cmdModifier)
                                .addGap(56, 56, 56)
                                .addComponent(cmdSupprimer))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addGap(223, 223, 223))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtprivilege, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtmatricule, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(txtnom)
                                    .addComponent(txtprenom)
                                    .addComponent(txtemail)
                                    .addComponent(txtadresse)
                                    .addComponent(txttelephone)
                                    .addComponent(txtstatut)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprivilege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtstatut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdModifier)
                    .addComponent(cmdajoutpersonnel)
                    .addComponent(cmdSupprimer))
                .addGap(48, 48, 48))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1216)/2, (screenSize.height-759)/2, 1216, 759);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn=(Connection) mysqlConnect.ConnectionDB();
       Majtable();
       remplirCombox();
       txtprivilege.setVisible(false);
       
    }//GEN-LAST:event_formWindowOpened

    private void cmdajoutpersonnelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdajoutpersonnelMouseClicked
        // TODO add your handling code here:
       // SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        //StringBuilder sb=new StringBuilder(sdf.format(jDateChooser1.getDate()));
        
        String sql="INSERT INTO `pointage`.`personnel` (`MATRICULE_PERSONNEL`, `ID_PRIVILEGE`, `NOM`, `PRENOM`, `EMAIL`, `ADRESSE`, `TELEPHONE`, `STATUT`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        try {
            requete=(PreparedStatement) conn.prepareStatement(sql);
            requete.setString(1, txtmatricule.getText());
            requete.setString(2, txtprivilege.getText());
            requete.setString(3, txtnom.getText());
            requete.setString(4, txtprenom.getText());
            requete.setString(5, txtemail.getText());
             //requete.setString(6, sb.toString());
            requete.setString(6, txtadresse.getText());
            requete.setString(7, txttelephone.getText());
            requete.setString(8, txtstatut.getText());
            requete.execute();
            Majtable();
            JOptionPane.showMessageDialog(null, "Ajouté");
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_cmdajoutpersonnelMouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        
        
        String libelleprivilege=(String)jComboBox1.getSelectedItem();
        String sql="select id_privilege from privilege where libelle=?";
        try {
            requete=(PreparedStatement) conn.prepareStatement(sql);
            requete.setString(1, libelleprivilege);
            resultat=requete.executeQuery();
            if(resultat.next()){
            id_privilege= resultat.getString("id_privilege");
            txtprivilege.setText(id_privilege);
            }
        } catch (SQLException ex) {
            Logger.getLogger(PersonnelJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void cmdSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdSupprimerMouseClicked

        
        
        String sql="DELETE FROM PERSONNEL WHERE matricule_personnel ="+txtmatricule.getText()+";";
        try {
            requete=(PreparedStatement) conn.prepareStatement(sql);
        requete.execute();
            Majtable();
            JOptionPane.showMessageDialog(null, "Suppréssion réussie!");
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        } 
                // TODO add your handling code here:
    }//GEN-LAST:event_cmdSupprimerMouseClicked

    private void cmdModifierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdModifierMouseClicked
        // TODO add your handling code here:
        
        
        
        String sql="UPDATE  `pointage`.`personnel` SET  MATRICULE_PERSONNEL=?, `NOM` =  ? ,"+
"`PRENOM` = ? ,"+
"`EMAIL` =  ? ,"+
"`ADRESSE` =  ? ,"+
"`TELEPHONE` =  ? ,"+
"`STATUT` =  ? WHERE  `personnel`.`MATRICULE_PERSONNEL` ="+txtmatricule.getText()+";";
        try {
            requete=(PreparedStatement) conn.prepareStatement(sql);
            requete.setString(1, txtmatricule.getText());
           
            requete.setString(2, txtnom.getText());
            requete.setString(3, txtprenom.getText());
            requete.setString(4, txtemail.getText());
              requete.setString(5, txtadresse.getText());
           
            requete.setString(6, txttelephone.getText());
            requete.setString(7, txtstatut.getText());
            requete.executeUpdate();
            Majtable();
            JOptionPane.showMessageDialog(null, "Mise à jour réussie!");
            
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, ex);
        } 
        
        
        
        
    }//GEN-LAST:event_cmdModifierMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
      //  LecteurTexte l=new LecteurTexte();
        
        int raw=jTable1.getSelectedRow();
        txtmatricule.setText(jTable1.getModel().getValueAt(raw, 0).toString());
         txtnom.setText(jTable1.getModel().getValueAt(raw, 1).toString());
          txtprenom.setText(jTable1.getModel().getValueAt(raw, 2).toString());
           txtemail.setText(jTable1.getModel().getValueAt(raw, 3).toString());
            txtadresse.setText(jTable1.getModel().getValueAt(raw, 4).toString());
             txttelephone.setText(jTable1.getModel().getValueAt(raw, 5).toString());
              txtstatut.setText(jTable1.getModel().getValueAt(raw, 6).toString());
         //     l.setTexte(txtnom.getText().toString()+" "+txtprenom.getText().toString());
          //   l.play();
             
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonnelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonnelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonnelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonnelJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PersonnelJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdModifier;
    private javax.swing.JButton cmdSupprimer;
    private javax.swing.JButton cmdajoutpersonnel;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtmatricule;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtprivilege;
    private javax.swing.JTextField txtstatut;
    private javax.swing.JTextField txttelephone;
    // End of variables declaration//GEN-END:variables
}
